using System;
using System.Collections.Generic;
using System.Linq;
using The_Boeing_737NG_App.Models;

namespace The_Boeing_737NG_App.Services
{
    public interface ICircuitBreakerService
    {
        List<CircuitBreaker> Search(string query);
    }
    public class CircuitBreakerService : ICircuitBreakerService
    {
        List<CircuitBreaker> CircuitBreakerList = default(List<CircuitBreaker>);
        public static CircuitBreakerService Instance() => new CircuitBreakerService();
        public CircuitBreakerService()
        {
            InitializeCircuitBreaker();
        }

        private void InitializeCircuitBreaker()
        {
            CircuitBreakerList = new List<CircuitBreaker>()
            {
                new CircuitBreaker() { System = "AC Bus 1, A phase", Panel = "P6-4", Location = "B13" },
                new CircuitBreaker() { System = "AC Bus 1, B phase", Panel = "P6-4", Location = "B14" },
                new CircuitBreaker() { System = "AC Bus 1, C phase", Panel = "P6-4", Location = "B15" },
                new CircuitBreaker() { System = "AC Bus 2, A phase", Panel = "P6-4", Location = "B10" },
                new CircuitBreaker() { System = "AC Bus 2, B phase", Panel = "P6-4", Location = "B11" },
                new CircuitBreaker() { System = "AC Bus 2, C phase", Panel = "P6-4", Location = "B12" },
                new CircuitBreaker() { System = "AC Bus, No 1 Electronics", Panel= "P18-0", Location = "2" },
                new CircuitBreaker() { System = "AC Generator 1, Indicator", Panel = "P91", Location = "B12" },
                new CircuitBreaker() { System = "AC Generator 2, Indicator", Panel = "P92", Location = "B12" },
                new CircuitBreaker() { System = "AC Standby Bus Power", Panel = "P6-4", Location = "D18" },
                new CircuitBreaker() { System = "AC Transfer Bus 1, A phase", Panel = "P6-4", Location = "C13" },
                new CircuitBreaker() { System = "AC Transfer Bus 1, B phase", Panel = "P6-4", Location = "C14" },
                new CircuitBreaker() { System = "AC Transfer Bus 1, C phase", Panel = "P6-4", Location = "C15" },
                new CircuitBreaker() { System = "AC Transfer Bus 2, A phase", Panel = "P6-4", Location = "C10" },
                new CircuitBreaker() { System = "AC Transfer Bus 2, B phase", Panel = "P6-4", Location = "C11" },
                new CircuitBreaker() { System = "ACARS MU AC", Panel = "P6-1", Location = "E7" },
                new CircuitBreaker() { System = "ACARS CMU AC", Panel = "P6-1", Location = "E8" },
                new CircuitBreaker() { System = "ACARS CMU DC", Panel = "P6-1", Location = "E9" },
                new CircuitBreaker() { System = "ACMS", Panel = "P6-1", Location = "E4" },
                new CircuitBreaker() { System = "ADF 1", Panel = "P18-1", Location = "A4" },
                new CircuitBreaker() { System = "ADF 2", Panel = "P6-1", Location = "A17" },
                new CircuitBreaker() { System = "ADIRU, Left, DC", Panel = "P18-1", Location = "E5" },
                new CircuitBreaker() { System = "ADIRU, Left, AC", Panel = "P18-1", Location = "E7" },
                new CircuitBreaker() { System = "ADIRU, Right, AC", Panel = "P6-1", Location = "C14" },
                new CircuitBreaker() { System = "ADIRU, Left, EXC", Panel = "P18-2", Location = "E8" },
                new CircuitBreaker() { System = "ADIRU, Right, EXC", Panel = "P6-1", Location = "C15" },
                new CircuitBreaker() { System = "ADIRU, Right, DC", Panel = "P6-1", Location = "C17" },
                new CircuitBreaker() { System = "AFCS, Sys A, FCC (DC)", Panel = "P18-1", Location = "D2" },
                new CircuitBreaker() { System = "AFCS, Sys A, Engage Interlock", Panel = "P18-1", Location = "D3" },
                new CircuitBreaker() { System = "AFCS, Sys A, Mach Trim (AC)", Panel = "P18-1", Location = "C4" },
                new CircuitBreaker() { System = "AFCS, Sys A, Mach Trim (DC)", Panel = "P18-1", Location = "D4" },
                new CircuitBreaker() { System = "AFCS, Sys A, Sensor Exc (AC)", Panel = "P18-1", Location = "C5" },
                new CircuitBreaker() { System = "AFCS, Sys A, Warn Light (Bat)", Panel = "P18-1", Location = "D1" },
                new CircuitBreaker() { System = "AFCS, Sys B, FCC (DC)", Panel = "P6-2", Location = "B3" },
                new CircuitBreaker() { System = "AFCS, Sys B, Engange Interlock", Panel = "P6-2", Location = "B4" },
                new CircuitBreaker() { System = "AFCS, Sys B, Mach Trim (AC)", Panel = "P6-2", Location = "C1" },
                new CircuitBreaker() { System = "AFCS, Sys B, Mach Trim (DC)", Panel = "P6-2", Location = "B2" },
                new CircuitBreaker() { System = "AFCS, Sys B, Sensor Exc (AC)", Panel = "P6-2", Location = "C2" },
                new CircuitBreaker() { System = "AFCS, Sys B, Warn Light (Bat)", Panel = "P6-2", Location = "B1" },
                new CircuitBreaker() { System = "Air Cond Bleed Air, Press Ind", Panel = "P6-4", Location = "B5" },
                new CircuitBreaker() { System = "Air Cond Bleed Air, Valve Isln", Panel = "P6-4", Location = "A5" },
                new CircuitBreaker() { System = "Air Cond Bleed Air, Valves Left", Panel = "P6-4", Location = "A7" },
                new CircuitBreaker() { System = "Air Cond Bleed Air, Valves Right", Panel = "P6-4", Location = "B7" },
                new CircuitBreaker() { System = "Air Cond Bleed Air, XDCR Left", Panel = "P6-4", Location = "A6" },
                new CircuitBreaker() { System = "Air Cond Bleed Air, XDCR, Right", Panel = "P6-4", Location = "B6" },
                new CircuitBreaker() { System = "Air Cond Compt Lt", Panel = "P92", Location = "C3" },
                new CircuitBreaker() { System = "Air Cond Mix Valve Pos Ind", Panel = "P6-4", Location = "D7" },
                new CircuitBreaker() { System = "Air Cond Overboard Exhaust Valve, Cont", Panel = "P6-4", Location = "D1" },
                new CircuitBreaker() { System = "Air Cond Overboard Exhaust Valve, Reconfig Cont", Panel = "P6-4", Location = "D2" },
                new CircuitBreaker() { System = "Air Cond Overheat", Panel = "P6-4", Location = "C4" },
                new CircuitBreaker() { System = "Air Cond Pack/Eng Bleed Air, Overheat, Left", Panel = "P6-4", Location = "C8" },
                new CircuitBreaker() { System = "Air Cond Pack/Eng Bleed Air, Overheat, Right", Panel = "P6-4", Location = "C7" },
                new CircuitBreaker() { System = "Air Cond Pack Controller, Left Electronic DC", Panel = "P6-4", Location = "A9" },
                new CircuitBreaker() { System = "Air Cond Pack Controller, Left Electronic AC", Panel = "P6-4", Location = "A11" },
                new CircuitBreaker() { System = "Air Cond Pack Controller, Right Electronic DC", Panel = "P6-4", Location = "B9" },
                new CircuitBreaker() { System = "Air Cond Pack Controller, Right Electronic AC", Panel = "P6-4", Location = "B11" },
                new CircuitBreaker() { System = "Air Cond Pack Cont Valve, Left", Panel = "P6-4", Location = "C6" },
                new CircuitBreaker() { System = "Air Cond Pack Cont Valve, Right", Panel = "P6-4", Location = "C5" },
                new CircuitBreaker() { System = "Air Cond Ram Air Mod Cont, Left", Panel = "P6-4", Location ="A8" },
                new CircuitBreaker() { System = "Air Cond Ram Air Mod Cont, Right", Panel = "P6-4", Location = "B8" },
                new CircuitBreaker() { System = "Air Cond Ram Air Mod Left", Panel = "P6-4", Location = "A4" },
                new CircuitBreaker() { System = "Air Cond Ram Air Mod Right", Panel = "P6-4", Location = "B4" },
                new CircuitBreaker() { System = "Air Cond Recirc Fan, Cabin", Panel = "P6-4", Location = "E4" },
                new CircuitBreaker() { System = "Air Cond Recirc Fan, Control", Panel = "P6-4", Location ="E1" },
                new CircuitBreaker() { System = "Air Cond Recirc Fan, Right Cont", Panel = "P6-4", Location ="E2" },
                new CircuitBreaker() { System = "Air Cond Recirc Fan, Right Cabin Air", Panel = "P6-4", Location = "E4" },
                new CircuitBreaker() { System = "Air Cond Temp Control, 35°F Left", Panel = "P6-4", Location = "A1" },
                new CircuitBreaker() { System = "Air Cond Temp Control, 35°F Right", Panel = "P6-4", Location = "B1" },
                new CircuitBreaker() { System = "Air Cond Temp Control, Auto Left", Panel = "P6-4", Location = "A2" },
                new CircuitBreaker() { System = "Air Cond Temp Control, Auto Right", Panel = "P6-4", Location = "B2" },
                new CircuitBreaker() { System = "Air Cond Temp Control, Manual", Panel = "P6-4", Location = "A3" },
                new CircuitBreaker() { System = "Air Cond Temp Control Valve Close Left", Panel = "P6-4", Location = "A1" },
                new CircuitBreaker() { System = "Air Cond Temp Control Valve Close Right", Panel = "P6-4", Location ="B1" },
                new CircuitBreaker() { System = "Air Cond Temp Ind", Panel = "P6-4", Location = "D8" },
                new CircuitBreaker() { System = "Air Cond Temp Valve/Fan Cont, Aft Pass", Panel = "P6-4", Location = "A3" },
                new CircuitBreaker() { System = "Air Cond Temp Valve/Fan Cont, Fwd Pass", Panel = "P6-4", Location = "B2" },
                new CircuitBreaker() { System = "Air Cond Temp Valve/Fan Cont, Flt Deck", Panel = "P6-4", Location = "B3" },
                new CircuitBreaker() { System = "Air Cond Trim Air Press", Panel = "P6-4", Location = "D9" },
                new CircuitBreaker() { System = "Air Cond Zone Temp, Duct Ovht, Aft Pass", Panel = "P6-4", Location = "C2" },
                new CircuitBreaker() { System = "Air Cond Zone Temp, Duct Ovht, Fwd Pass", Panel = "P6-4" },
                new CircuitBreaker() { System = "Air Cond Zone Temp, Duct Ovht, Flt Deck", Panel = "P6-4" },
                new CircuitBreaker() { System = "Airfone", Panel = "P6-1", Location = "E2" },
                new CircuitBreaker() { System = "Airstair, Actuator (3phase)", Panel = "P6-4", Location = "B17" },
                new CircuitBreaker() { System = "Airstair, Cont", Panel = "P6-4", Location = "A17" },
                new CircuitBreaker() { System = "Airstair, Door", Panel = "P6-4", Location = "A16" },
                new CircuitBreaker() { System = "Airstair, Stby Door", Panel = "P6-4", Location = "C16" },
                new CircuitBreaker() { System = "Airstair, Stby Cont & Iwd Ent Door Ind", Panel = "P6-4", Location = "C17" },
                new CircuitBreaker() { System = "Airstair, Tread lights", Panel = "P6-4", Location = "A18" },
                new CircuitBreaker() { System = "Alternate T.E. Flap Drive", Panel = "P6-2", Location = "D13" },
                new CircuitBreaker() { System = "Anti-Ice, Alpha Vane Heater, Left", Panel = "P18-3", Location = "C3" },
                new CircuitBreaker() { System = "Anti-Ice, Alpha Vane Heater, Right", Panel = "P18-3", Location = "D3" },
                new CircuitBreaker() { System = "Anti-Ice, Aux Pitot", Panel = "P18-3", Location = "D6" },
                new CircuitBreaker() { System = "Anti-Ice, Capt Pitot", Panel = "P18-3", Location = "C1" },
                new CircuitBreaker() { System = "Anti-Ice, Drain Heater", Panel = "P18-3", Location = "E5" },
                new CircuitBreaker() { System = "Anti-Ice, Drain Mast Heater, Air", Panel = "P18-3", Location = "E4" },
                new CircuitBreaker() { System = "Anti-Ice, Elevator Pitot, Left", Panel = "P18-3", Location = "C4" },
                new CircuitBreaker() { System = "Anti-Ice, Elevator Pitot, Right", Panel = "P18-3", Location = "D4" },
                new CircuitBreaker() { System = "Anti-Ice, Engine 1, Cowl Anti-Ice Valve", Panel = "P18-3", Location = "A7" },
                new CircuitBreaker() { System = "Anti-Ice, Engine 1, Engine and Wing Control", Panel = "P18-3", Location = "A6" },
                new CircuitBreaker() { System = "Anti-Ice, Engine 2, Cowl Anti-Ice Valve", Panel = "P18-3", Location = "B7" },
                new CircuitBreaker() { System = "Anti-Ice, Engine 2, Control", Panel = "P18-3", Location = "B6" },
                new CircuitBreaker() { System = "Anti-Ice, F/O Pitot", Panel = "P18-3", Location = "D5" },
                new CircuitBreaker() { System = "Anti-Ice, Hose Heaters", Panel = "P18-3", Location = "F16" },
                new CircuitBreaker() { System = "Anti-Ice, Master Caution", Panel = "P6-3", Location = "D9" },
                new CircuitBreaker() { System = "Anti-Ice, Temp Probe", Panel = "P18-3", Location = "C2" },
                new CircuitBreaker() { System = "Anti-Ice, Windshield Wiper, Left", Panel = "P18-3", Location = "B3" },
                new CircuitBreaker() { System = "Anti-Ice, Windshield Wiper, Right", Panel = "P18-3", Location = "B1" },
                new CircuitBreaker() { System = "Anti-Ice, Wing Anti-Ice Valve", Panel = "P18-3", Location = "A1" },
                new CircuitBreaker() { System = "Anti-Skid, Inboard", Panel = "P6-3", Location = "E16" },
                new CircuitBreaker() { System = "Anti-Skid, Outboard", Panel = "P6-3", Location = "E18" },
                new CircuitBreaker() { System = "APU AC Gen Ind", Panel = "P91", Location = "B11 | C11" },
                new CircuitBreaker() { System = "APU Control", Panel = "P6-4", Location = "A14" },
                new CircuitBreaker() { System = "APU Fan Power", Panel = "P6-4", Location = "B14" },
                new CircuitBreaker() { System = "APU Fire Detection", Panel = "P6-2", Location = "A23" },
                new CircuitBreaker() { System = "APU Fire Extinguisher Bottle", Panel = "P6-2", Location = "C23" },
                new CircuitBreaker() { System = "APU Fire Switch Power", Panel = "P6-2", Location = "B19" },
                new CircuitBreaker() { System = "APU Fuel Boost Pump", Panel = "P6-4", Location = "A12" },
                new CircuitBreaker() { System = "APU Gen Control Unit", Panel = "P6-4", Location = "F12" },
                new CircuitBreaker() { System = "APU Gen Control Unit", Panel = "P92", Location = "C9" },
                new CircuitBreaker() { System = "APU Start", Panel = "P18-5", Location = "" },
                new CircuitBreaker() { System = "APU Start Conv", Panel = "P91", Location = "A11" },
                new CircuitBreaker() { System = "ATC 1", Panel = "P18-1", Location = "B5" },
                new CircuitBreaker() { System = "ATC 2", Panel = "P6-1", Location = "D14" },
                new CircuitBreaker() { System = "ATC, Ant Switch", Panel = "P6-1", Location = "E14" },
                new CircuitBreaker() { System = "ATS Call", Panel = "P18-2", Location = "D14" },
                new CircuitBreaker() { System = "Audio, Capt", Panel = "P6-2", Location = "D23" },
                new CircuitBreaker() { System = "Audio, F/O", Panel = "P6-2", Location = "D22" },
                new CircuitBreaker() { System = "Audio, Obs", Panel = "P6-2", Location = "D24" },
                new CircuitBreaker() { System = "Aural Warn", Panel = "P6-2", Location = "D18" },
                new CircuitBreaker() { System = "Auto Brakes Control", Panel = "P6-3", Location = "A17" },
                new CircuitBreaker() { System = "Auto Brake Cont 1", Panel = "P6-3", Location = "A18" },
                new CircuitBreaker() { System = "Auto Brake Cont 2", Panel = "P6-3", Location = "A16" },
                new CircuitBreaker() { System = "Auto Slat DC 1", Panel = "P6-2", Location = "C14" },
                new CircuitBreaker() { System = "Auto Slat DC 2", Panel = "P6-2", Location = "B14" },
                new CircuitBreaker() { System = "Auto Speed Brake", Panel = "P6-2", Location = "B9" },
                new CircuitBreaker() { System = "Auto Throttle DC 1", Panel = "P18-1", Location = "E1" },
                new CircuitBreaker() { System = "Auto Throttle DC 2", Panel = "P18-1", Location = "E3" },
                new CircuitBreaker() { System = "Aux Battery Charger", Panel = "P91", Location = "E3" },
                new CircuitBreaker() { System = "Aux Power Unit Cont", Panel = "P6-4", Location = "A14" },
                new CircuitBreaker() { System = "Aux Power Unit SCU Fan Power", Panel = "P6-4", Location = "B14" },
                new CircuitBreaker() { System = "Bat Bus, Sect 1", Panel = "P6-5", Location = "C4" },
                new CircuitBreaker() { System = "Bat Bus, Sect 2", Panel = "P6-5", Location = "C5" },
                new CircuitBreaker() { System = "Bat Bus, Sect 3", Panel = "P6-5", Location = "A1" },
                new CircuitBreaker() { System = "Bat Charger", Panel = "P92", Location = "E1" },
                new CircuitBreaker() { System = "Bat/Stby, Sw Pos Ind", Panel = "P6-5", Location = "B5" },
                new CircuitBreaker() { System = "Bleed Air, Overheat, Right", Panel = "P6-4", Location = "C7" },
                new CircuitBreaker() { System = "Bleed Air, Overheat, Left", Panel = "P6-4", Location = "C8" },
                new CircuitBreaker() { System = "Bleed Air, Press Ind", Panel = "P6-4", Location = "B5" },
                new CircuitBreaker() { System = "Bleed Air, Valve Isln", Panel = "P6-4", Location = "A5" },
                new CircuitBreaker() { System = "Bleed Air, Valves Left", Panel = "P6-4", Location = "A7" },
                new CircuitBreaker() { System = "Bleed Air, Valves Right", Panel = "P6-4", Location = "B7" },
                new CircuitBreaker() { System = "Bleed Air, XDCR Left", Panel = "P6-4", Location = "A6" },
                new CircuitBreaker() { System = "Bleed Air, XDCR Right", Panel = "P6-4", Location = "B6" },
                new CircuitBreaker() { System = "Boost Pump, Tank, Center Left", Panel = "P91", Location = "D6" },
                new CircuitBreaker() { System = "Boost Pump, Tank, Center Right", Panel = "P92", Location = "D2" },
                new CircuitBreaker() { System = "Boost Pump, Tank 1, Aft", Panel = "P92", Location = "D2" },
                new CircuitBreaker() { System = "Boost Pump, Tank 1, Fwd", Panel = "P91", Location = "D2" },
                new CircuitBreaker() { System = "Boost Pump, Tank 2 Aft", Panel = "P91", Location = "D4" },
                new CircuitBreaker() { System = "Boost Pump, Tank 2 Fwd", Panel = "P92", Location = "D4" },
                new CircuitBreaker() { System = "Brake Pressure Indicator", Panel = "P6-2", Location = "A13" },
                new CircuitBreaker() { System = "Brakes, Anti-Skid, Inboard", Panel = "P6-3", Location = "E16" },
                new CircuitBreaker() { System = "Brakes, Anti-Skid, Outboard", Panel = "P6-3", Location = "E18" },
                new CircuitBreaker() { System = "Bus Power Control Unit", Panel = "P6-4", Location = "F13" },
                new CircuitBreaker() { System = "Bus Power Control Unit", Panel = "P91", Location = "C10" },
                new CircuitBreaker() { System = "C/B NATS", Panel = "P6-1", Location = "E2" },
                new CircuitBreaker() { System = "Clock", Panel = "P6-3", Location = "A2" },
                new CircuitBreaker() { System = "Cargo Fire, Ext 2", Panel = "P18-3", Location = "B16" },
                new CircuitBreaker() { System = "Cargo Fire, Ext 1", Panel = "P18-3", Location = "B17" },
                new CircuitBreaker() { System = "Cargo Fire, Fwd Det B", Panel = "P18-3", Location = "C16" },
                new CircuitBreaker() { System = "Cargo Fire, Fwd Det A", Panel = "P18-3", Location = "C17" },
                new CircuitBreaker() { System = "Cargo Fire, Aft Det B", Panel = "P18-3", Location = "C18" },
                new CircuitBreaker() { System = "Cargo Fire, Aft Det A", Panel = "P18-3", Location = "C19" },
                new CircuitBreaker() { System = "Cargo Light Cont", Panel = "P92", Location = "C10" },
                new CircuitBreaker() { System = "Cargo Loader Cont, Aft", Panel = "P6-11", Location = "D8" },
                new CircuitBreaker() { System = "Cargo Loader Cont, Fwd", Panel = "P6-12", Location = "D8" },
                new CircuitBreaker() { System = "Cargo Loader Drive, Aft", Panel = "P91", Location = "E8" },
                new CircuitBreaker() { System = "Cargo Loader Drive, Fwd", Panel = "P92", Location = "E4" },
                new CircuitBreaker() { System = "CDU 1", Panel = "P18-2", Location = "A7" },
                new CircuitBreaker() { System = "CDU 2", Panel = "P6-1", Location = "D15" },
                new CircuitBreaker() { System = "Clock, Misc", Panel = "P6-3", Location = "A2" },
                new CircuitBreaker() { System = "Clock, Display", Panel = "P6-3", Location = "A1" },
                new CircuitBreaker() { System = "CMU, ACARS, DC", Panel = "P6-1", Location = "E9" },
                new CircuitBreaker() { System = "CMU-1 AC", Panel = "P6-1", Location = "E8" },
                new CircuitBreaker() { System = "CMU-2 AC", Panel = "P6-1", Location = "E7" },
                new CircuitBreaker() { System = "Coffee Maker 1 & 2, Aft Galley", Panel = "Aft Galley", Location = "" },
                new CircuitBreaker() { System = "Coffee Maker, Forward Galley", Panel = "Fwd Galley", Location = "" },
                new CircuitBreaker() { System = "Communications, HF1", Panel = "P18-2", Location = "E11" },
                new CircuitBreaker() { System = "Communications, HF2", Panel = "P6-1", Location = "D2" },
                new CircuitBreaker() { System = "Communications, VHF 1", Panel = "P18-2", Location = "D11" },
                new CircuitBreaker() { System = "Communications, VHF 2", Panel = "P6-1", Location = "C3" },
                new CircuitBreaker() { System = "Communications, VHF 3", Panel = "P18-2", Location = "D12" },
                new CircuitBreaker() { System = "Compass 1, Alternate Transformer", Panel = "P6-1", Location = "B12" },
                new CircuitBreaker() { System = "Compass 2, Alternate Transformer", Panel = "P18-2", Location = "B3" },
                new CircuitBreaker() { System = "Computer, Air Data 1 (26V AC)", Panel = "P18-2", Location = "A9" },
                new CircuitBreaker() { System = "Computer, Air Data 1 (AC)", Panel = "P18-2", Location = "A8" },
                new CircuitBreaker() { System = "Computer, Air Data 2 (26V AC)", Panel = "P6-1", Location = "B6" },
                new CircuitBreaker() { System = "Computer, Air Data 2 (AC)", Panel = "P6-1", Location = "B7" },
                new CircuitBreaker() { System = "Computer, FMCS", Panel = "P18-2", Location = "E8" },
                new CircuitBreaker() { System = "Cowl Anti-Ice Valve, Engine 1", Panel = "P18-3", Location = "A7" },
                new CircuitBreaker() { System = "Cowl Anti-Ice Valve, Engine 2", Panel = "P18-3", Location = "B7" },
                new CircuitBreaker() { System = "Crew Call", Panel = "P18-3", Location = "A9" },
                new CircuitBreaker() { System = "Cross Feed Valve", Panel = "P6-3", Location = "B7" },
                new CircuitBreaker() { System = "Data Loader", Panel = "P18-2", Location = "A9" },
                new CircuitBreaker() { System = "DC Bus 1, Sect 2", Panel = "P91", Location = "C12" },
                new CircuitBreaker() { System = "DC Bus 1, Sect 1", Panel = "P91", Location = "A2" },
                new CircuitBreaker() { System = "DC Bus 2, Sect 1", Panel = "P92", Location = "C12" },
                new CircuitBreaker() { System = "DC Bus 2, Sect 2", Panel = "P92", Location = "A2" },
                new CircuitBreaker() { System = "DC Bus 1 XFR", Panel = "P91", Location = "A1" },
                new CircuitBreaker() { System = "DC Bus 2 XFR", Panel = "P92", Location = "A1" },
                new CircuitBreaker() { System = "DC Bus Indication, Bat", Panel = "P6-4", Location = "F14" },
                new CircuitBreaker() { System = "DC Bus Indication, Bus 1", Panel = "P6-4", Location = "F16" },
                new CircuitBreaker() { System = "DC Bus Indication, Bus 2", Panel = "P6-4", Location = "F18" },
                new CircuitBreaker() { System = "DC Bus Indication, Hot Bat", Panel = "P6-4", Location = "E15" },
                new CircuitBreaker() { System = "DC Bus Indication, Sw Hot Bat", Panel = "P6-4", Location = "E16" },
                new CircuitBreaker() { System = "DC Bus Indication, Stby", Panel = "P6-4", Location = "E18" },
                new CircuitBreaker() { System = "Display, Capt EFIS Control Panel", Panel = "P18-2", Location = "D1" },
                new CircuitBreaker() { System = "Display, Capt Inbd", Panel = "P18-2", Location = "D3" },
                new CircuitBreaker() { System = "Display, Capt Outbd", Panel = "P18-2", Location = "D4" },
                new CircuitBreaker() { System = "Display, Ctr Lwr", Panel = "P6-1", Location = "E12" },
                new CircuitBreaker() { System = "Display, Ctr Upr", Panel = "P18-2", Location = "D2" },
                new CircuitBreaker() { System = "Display, DEU 1 Holdup", Panel = "P6-1", Location = "D10" },
                new CircuitBreaker() { System = "Display, DEU 1 Pri", Panel = "P18-2", Location = "D5" },
                new CircuitBreaker() { System = "Display, DEU 2 Holdup", Panel = "P6-1", Location = "D9" },
                new CircuitBreaker() { System = "Display, DEU 2 Pri", Panel = "P6-1", Location = "D11" },
                new CircuitBreaker() { System = "Display, F/O EFIS Control Panel", Panel = "P6-1", Location = "E13" },
                new CircuitBreaker() { System = "Display, F/O Inbd", Panel = "P6-1", Location = "E11" },
                new CircuitBreaker() { System = "Display, F/O Outbd", Panel = "P6-1", Location = "E10" },
                new CircuitBreaker() { System = "DME 1", Panel = "P18-1", Location = "B3" },
                new CircuitBreaker() { System = "DME 2", Panel = "P6-1", Location = "A14" },
                new CircuitBreaker() { System = "Door Area Heater - Fwd", Panel = "P91", Location = "A16" },
                new CircuitBreaker() { System = "Door Area Heater - Aft", Panel = "P91", Location = "A14" },
                new CircuitBreaker() { System = "Door Area Heat Cont", Panel = "P18-3", Location = "E11" },
                new CircuitBreaker() { System = "Door Lock", Panel = "P6-3", Location = "E1" },
                new CircuitBreaker() { System = "Dual Bat RCCB Remote", Panel = "P6-5", Location = "A4" },
                new CircuitBreaker() { System = "E/C Power", Panel = "P6-12", Location = "A8" },
                new CircuitBreaker() { System = "EFIS, Cont Panel, Capt", Panel = "P18-2", Location = "D1" },
                new CircuitBreaker() { System = "EFIS, Cont Panel, F/O", Panel = "P6-1", Location = "E13" },
                new CircuitBreaker() { System = "Electrical, AC Bus, Stby Bus, 28v AC Disc", Panel = "P6-4", Location = "D15" },
                new CircuitBreaker() { System = "Electrical, AC Bus, Stby Bus, 115v AC Ind", Panel = "P6-4", Location = "D16" },
                new CircuitBreaker() { System = "Electrical, AC Stby Bus Pwr", Panel = "P6-4", Location = "D18" },
                new CircuitBreaker() { System = "Electrical, Gnd Svc DC Hot Bat", Panel = "P6-4", Location = "E12" },
                new CircuitBreaker() { System = "Electrical, Gnd Svc Cont", Panel = "P6-4", Location = "E13" },
                new CircuitBreaker() { System = "Electrical, TR3 XFR Relay Cont", Panel = "P6-4", Location = "E11" },
                new CircuitBreaker() { System = "Electrical, Transfer Bus 1, 26v AC, Sect 2", Panel = "P18-3", Location = "C5" },
                new CircuitBreaker() { System = "Electrical, Transfer Bus 2, 115v AC Ind", Panel = "P6-4", Location = "D13" },
                new CircuitBreaker() { System = "Electrical, Transfer Bus 2, 26v AC, Sect 2", Panel = "P6-4", Location = "D14" },
                new CircuitBreaker() { System = "Elevator Tab Valve Right", Panel = "P6-2", Location = "B8" },
                new CircuitBreaker() { System = "Elex Panel lights, Capt fwd/aft, Centr, F/O", Panel = "Aft Pedestral", Location = "" },
                new CircuitBreaker() { System = "Eng 1, Alt Pwr, Channel B", Panel = "P18-2", Location = "A4" },
                new CircuitBreaker() { System = "Eng 2, Alt Pwr, Channel B", Panel = "P6-2", Location = "D7" },
                new CircuitBreaker() { System = "Eng 1, Alt Pwr, Channel A", Panel = "P18-2", Location = "A5" },
                new CircuitBreaker() { System = "Eng 2, Alt Pwr, Channel A", Panel = "P6-2", Location = "D8" },
                new CircuitBreaker() { System = "Eng 1, Engine & Wing Control", Panel = "P18-3", Location = "A6" },
                new CircuitBreaker() { System = "Eng 2, Engine Control", Panel = "P18-3", Location = "B6" },
                new CircuitBreaker() { System = "Eng 1, Ignition, Left", Panel = "P18-2", Location = "A3" },
                new CircuitBreaker() { System = "Eng 1, Ignition, Right", Panel = "P18-2", Location = "A1" },
                new CircuitBreaker() { System = "Eng 2, Ignition, Left", Panel = "P6-2", Location = "D6" },
                new CircuitBreaker() { System = "Eng 2, Ignition, Right", Panel = "P6-2", Location = "D4" },
                new CircuitBreaker() { System = "Eng 1, Run/Pwr", Panel = "P18-2", Location = "B3" },
                new CircuitBreaker() { System = "Eng 2, Run/Pwr", Panel = "P6-2", Location = "B5" },
                new CircuitBreaker() { System = "Eng 1, Start Lever, Channel A", Panel = "P18-2", Location = "B1" },
                new CircuitBreaker() { System = "Eng 1, Start Lever, Channel B", Panel = "P18-2", Location = "B2" },
                new CircuitBreaker() { System = "Eng 2, Start Lever, Channel A", Panel = "P6-2", Location = "B6" },
                new CircuitBreaker() { System = "Eng 2, Start Lever, Channel B", Panel = "P6-2", Location = "B7" },
                new CircuitBreaker() { System = "Eng 1, Start Valve", Panel = "P18-2", Location = "B8" },
                new CircuitBreaker() { System = "Eng 2, Start Valve", Panel = "P6-2", Location = "C4" },
                new CircuitBreaker() { System = "Eng Fuel, Eng 2, HPSOV Cont", Panel = "P6-3", Location = "E3" },
                new CircuitBreaker() { System = "Eng Fuel, Eng 2, HPSOV Ind", Panel = "P6-3", Location = "E4" },
                new CircuitBreaker() { System = "Eng Fuel, Eng 1, HPSOV Cont", Panel = "P6-3", Location = "E5" },
                new CircuitBreaker() { System = "Eng Fuel, Eng 1, HPSOV Ind", Panel = "P6-3", Location = "E6" },
                new CircuitBreaker() { System = "Eng Pump Depress Valve 1", Panel = "P6-2", Location = "B15" },
                new CircuitBreaker() { System = "Eng Pump Depress Valve 1", Panel = "P6-2", Location = "B" },
                new CircuitBreaker() { System = "Engine Vibration Monitor", Panel = "P6-2", Location = "A2" },
                new CircuitBreaker() { System = "Entertainment, Audio, LH", Panel = "P6-1", Location = "C7" },
                new CircuitBreaker() { System = "Entertainment, Audio, RH", Panel = "P6-1", Location = "C8" },
                new CircuitBreaker() { System = "Entertainment, Audio, PA Tape RPDR (AC)", Panel = "P6-1", Location = "C9" },
                new CircuitBreaker() { System = "Entertainment, Audio, ENT VID CTR-DC", Panel = "P6-1", Location = "C10" },
                new CircuitBreaker() { System = "Entertainment, Audio, ENT VID CTR-AC", Panel = "P6-1", Location = "C11" },
                new CircuitBreaker() { System = "Entertainment, Audio, Video 1", Panel = "P6-1", Location = "C12" },
                new CircuitBreaker() { System = "Entertainment, Audio, Video 2", Panel = "P6-1", Location = "C13" },
                new CircuitBreaker() { System = "Entertainment, Audio, Video 3", Panel = "P6-1", Location = "C13" },
                new CircuitBreaker() { System = "Equipment Cooling Exhaust Fan Control, Altn", Panel = "P6-4", Location = "C15" },
                new CircuitBreaker() { System = "Equipment Cooling Exhaust Fan Control, Normal", Panel = "P6-4", Location = "C14" },
                new CircuitBreaker() { System = "Equipment Cooling Exhaust Fan Power - Normal", Panel = "P91", Location = "E1" },
                new CircuitBreaker() { System = "Equipment Cooling Exhaust Fan Power - Altn", Panel = "P92", Location = "A10" },
                new CircuitBreaker() { System = "Equipment Cooling Low Flow Dect, Supply", Panel = "P18-3", Location = "A17" },
                new CircuitBreaker() { System = "Equipment Cooling Low Flow Dect, Exhaust", Panel = "P18-3", Location = "A18" },
                new CircuitBreaker() { System = "Equipment Cooling Supply Fan Control, Altn", Panel = "P6-4", Location = "C13" },
                new CircuitBreaker() { System = "Equipment Cooling Supply Fan Control, Normal", Panel = "P6-4", Location = "C12" },
                new CircuitBreaker() { System = "Equipment Cooling Supply Fan Power, Altn", Panel = "P91", Location = "A8" },
                new CircuitBreaker() { System = "Equipment Cooling Supply Fan Power, Normal", Panel = "P92", Location = "A8" },
                new CircuitBreaker() { System = "Ext Pwr", Panel = "P91", Location = "A12" },
                new CircuitBreaker() { System = "Ext Pwr 1", Panel = "P92", Location = "A18" },
                new CircuitBreaker() { System = "Ext Pwr 2", Panel = "P92", Location = "A15" },
                new CircuitBreaker() { System = "Ext Pwr BPCU", Panel = "P92", Location = "A12" },
                new CircuitBreaker() { System = "Fasten Seat Belt, Left", Panel = "P18-3", Location = "C9" },
                new CircuitBreaker() { System = "Fasten Seat Belt, Right", Panel = "P18-3", Location = "C8" },
                new CircuitBreaker() { System = "FCC AFCS System B (DC)", Panel = "P6-2", Location = "B3" },
                new CircuitBreaker() { System = "Fire Detection, Ovrht, WW, Wing-Body", Panel = "P6-2", Location = "A19" },
                new CircuitBreaker() { System = "Fire Detection, APU", Panel = "P6-2", Location = "A23" },
                new CircuitBreaker() { System = "Fire Detection, Engine 1", Panel = "P6-2", Location = "A24" },
                new CircuitBreaker() { System = "Fire Detection, Engine 2", Panel = "P6-2", Location = "A22" },
                new CircuitBreaker() { System = "Fire Detection, MA Warn & Cont", Panel = "P6-2", Location = "A21" },
                new CircuitBreaker() { System = "Fire Extinguishers, APU", Panel = "P6-2", Location = "B21" },
                new CircuitBreaker() { System = "Fire Extinguishers, Right", Panel = "P6-2", Location = "B20" },
                new CircuitBreaker() { System = "Fire Extinguishers, Left", Panel = "P6-2", Location = "B22" },
                new CircuitBreaker() { System = "Fire Extinguishers, Altn Right", Panel = "P6-2", Location = "B23" },
                new CircuitBreaker() { System = "Fire Extinguishers, Altn, Left", Panel = "P6-2", Location = "B24" },
                new CircuitBreaker() { System = "Flaps Pos Ind, LE", Panel = "P6-2", Location = "C12" },
                new CircuitBreaker() { System = "Flight Control Flap Load Relief", Panel = "P6-2", Location = "A6" },
                new CircuitBreaker() { System = "Flight Control Flap Shutoff Valves", Panel = "P6-2", Location = "A7" },
                new CircuitBreaker() { System = "Flight Control Shutoff Valve, Flt Cont", Panel = "P6-2", Location = "B13" },
                new CircuitBreaker() { System = "Flight Control Shutoff Valve, Flt Cont", Panel = "P6-2", Location = "C13" },
                new CircuitBreaker() { System = "Flight Control Shutoff Valve, Spoiler", Panel = "P6-2", Location = "B12" },
                new CircuitBreaker() { System = "Flight Control Shutoff Valve, Stby Rud", Panel = "P6-2", Location = "C11" },
                new CircuitBreaker() { System = "Flight Control Altn T.E. Flap Drive", Panel = "P6-2", Location = "D13" },
                new CircuitBreaker() { System = "Flight Recorder AC", Panel = "P18-2", Location = "C9" },
                new CircuitBreaker() { System = "Flight Recorder DC", Panel = "P18-2", Location = "C10" },
                new CircuitBreaker() { System = "Flight Recorder, Position Sensor", Panel = "P18-2", Location = "C8" },
                new CircuitBreaker() { System = "FMCS Bite DC", Panel = "P18-2", Location = "B10" },
                new CircuitBreaker() { System = "FMCS CDU 1", Panel = "P18-2", Location = "A7" },
                new CircuitBreaker() { System = "FMCS CDU 2", Panel = "P6-1", Location = "D15" },
                new CircuitBreaker() { System = "FMCS, Cmptr No 1", Panel = "P18-2", Location = "E8 & A6" },
                new CircuitBreaker() { System = "FMCS, Cmptr 1", Panel = "P18-2", Location = "A6" },
                new CircuitBreaker() { System = "FMCS, Cmptr 2", Panel = "P6-1", Location = "D16" },
                new CircuitBreaker() { System = "FMCS, MCDU 1", Panel = "P18-2", Location = "A7" },
                new CircuitBreaker() { System = "FMCS, MCDU 2", Panel = "P6-1", Location = "D15" },
                new CircuitBreaker() { System = "FMCS, Xfr", Panel = "P6-1", Location = "E15" },
                new CircuitBreaker() { System = "FSEU DC 1", Panel = "P6-2", Location = "A8" },
                new CircuitBreaker() { System = "FSEU DC 2", Panel = "P6-2", Location = "A9" },
                new CircuitBreaker() { System = "Fuel Boost Pump, Center Tank Left", Panel = "P91", Location = "D6" },
                new CircuitBreaker() { System = "Fuel Boost Pump, Center Tank Right", Panel = "P92", Location = "D6" },
                new CircuitBreaker() { System = "Fuel Boost Pump, Tank 1, Aft", Panel = "P92", Location = "D2" },
                new CircuitBreaker() { System = "Fuel Boost Pump, Tank 1, Fwd", Panel = "P91", Location = "D2" },
                new CircuitBreaker() { System = "Fuel Boost Pump, Tank 2, Aft", Panel = "P91", Location = "D4" },
                new CircuitBreaker() { System = "Fuel Boost Pump, Tank 2, Fwd", Panel = "P92", Location = "D4" },
                new CircuitBreaker() { System = "Fuel Cont", Panel = "P6-3", Location = "A3" },
                new CircuitBreaker() { System = "Fuel Cross Feed Valve", Panel = "P6-3", Location = "B7" },
                new CircuitBreaker() { System = "Fuel, Eng 1, HPSOV Cont", Panel = "P6-3", Location = "E5" },
                new CircuitBreaker() { System = "Fuel, Eng 1, HPSOV Ind", Panel = "P6-3", Location = "E6" },
                new CircuitBreaker() { System = "Fuel, Eng 2, HPSOV Cont", Panel = "P6-3", Location = "E3" },
                new CircuitBreaker() { System = "Fuel, Eng 2, HPSOV Ind", Panel = "P6-3", Location = "E4" },
                new CircuitBreaker() { System = "Fuel Ind", Panel = "P6-3", Location = "A4" },
                new CircuitBreaker() { System = "Fuel Qty 1", Panel = "P6-3", Location = "A6" },
                new CircuitBreaker() { System = "Fuel Qty 2", Panel = "P6-3", Location = "A5" },
                new CircuitBreaker() { System = "Fuel Shutoff Valve, Bus", Panel = "P6-3", Location = "C6" },
                new CircuitBreaker() { System = "Fuel Shutoff Valve, Pwr Pack", Panel = "P6-3", Location = "C4" },
                new CircuitBreaker() { System = "Fuel Spar Valve, Eng 1", Panel = "P6-3", Location = "B4" },
                new CircuitBreaker() { System = "Fuel Spar Valve, Eng 2", Panel = "P6-3", Location = "B3" },
                new CircuitBreaker() { System = "Fuel Spar Valve Ind", Panel = "P6-3", Location = "B5" },
                new CircuitBreaker() { System = "Fuel Temp Ind", Panel = "P6-3", Location = "A7" },
                new CircuitBreaker() { System = "Galley Bus A", Panel = "P92", Location = "F7" },
                new CircuitBreaker() { System = "Galley Bus B", Panel = "P92", Location = "F8" },
                new CircuitBreaker() { System = "Galley Bus C", Panel = "P91", Location = "F7" },
                new CircuitBreaker() { System = "Galley Bus D", Panel = "P91", Location = "F8" },
                new CircuitBreaker() { System = "Gasper Fan", Panel = "P6-4", Location = "E7" },
                new CircuitBreaker() { System = "Gen 1 Load Shed", Panel = "P91", Location = "C7" },
                new CircuitBreaker() { System = "Gen 2 Load Shed", Panel = "P92", Location = "C7" },
                new CircuitBreaker() { System = "Generator Control Unit 1", Panel = "P6-4", Location = "F10" },
                new CircuitBreaker() { System = "Generator Control Unit 2", Panel = "P6-4", Location = "F11" },
                new CircuitBreaker() { System = "Generator, APU Gen Cont Unit", Panel = "P6-4", Location = "F12" },
                new CircuitBreaker() { System = "Generator, Bus Pwr Cont Unit", Panel = "P6-4", Location = "F13" },
                new CircuitBreaker() { System = "Generator Disc 1", Panel = "P6-4", Location = "F8" },
                new CircuitBreaker() { System = "Generator Disc 2", Panel = "P6-4", Location = "F9" },
                new CircuitBreaker() { System = "GPS 1/MMR 1", Panel = "P18-1", Location = "A7" },
                new CircuitBreaker() { System = "GPS 2/MMR 2", Panel = "P6-1", Location = "A9" },
                new CircuitBreaker() { System = "Grey Water Drain Valve", Panel = "P18-3", Location = "E19" },
                new CircuitBreaker() { System = "Ground Prox Warn", Panel = "P18-1", Location = "B7" },
                new CircuitBreaker() { System = "Ground Serv 1", Panel = "P91", Location = "F1" },
                new CircuitBreaker() { System = "Ground Serv 1, Sect 1", Panel = "P91", Location = "E5" },
                new CircuitBreaker() { System = "Ground Serv 1, 28vac", Panel = "P91", Location = "E11" },
                new CircuitBreaker() { System = "Ground Serv 2", Panel = "P92", Location = "F1" },
                new CircuitBreaker() { System = "Ground Serv 2, 28vac", Panel = "P92", Location = "E6" },
                new CircuitBreaker() { System = "Ground Serv Clg Night Cont", Panel = "P91", Location = "C4" },
                new CircuitBreaker() { System = "Ground Serv Cont", Panel = "P6-4", Location = "E13" },
                new CircuitBreaker() { System = "Ground Serv DC1", Panel = "P6-4", Location = "D11" },
                new CircuitBreaker() { System = "Ground Serv DC Hot Bat", Panel = "P6-4", Location = "E12" },
                new CircuitBreaker() { System = "Ground Serv Wdo Brt Cont", Panel = "P92", Location = "C1" },
                new CircuitBreaker() { System = "Heads Up Guidance, Cmptr Altn DC", Panel = "P18-2", Location = "C6" },
                new CircuitBreaker() { System = "Heads Up Guidance, Cmptr DC", Panel = "P18-2", Location = "C5" },
                new CircuitBreaker() { System = "Heads Up Guidance, Control Panel DC", Panel = "P18-2", Location = "C4" },
                new CircuitBreaker() { System = "Heads Up Guidance, DEU AC", Panel = "P18-2", Location = "C3" },
                new CircuitBreaker() { System = "Heads Up Guidance, DEU Altn AC", Panel = "P18-2", Location = "C1" },
                new CircuitBreaker() { System = "Heads Up Guidance, Pwr Mon AC", Panel = "P18-2", Location = "C2" },
                new CircuitBreaker() { System = "HF1", Panel = "P18-2", Location = "E11" },
                new CircuitBreaker() { System = "HF2", Panel = "P6-1", Location = "D2" },
                new CircuitBreaker() { System = "Hose Heaters", Panel = "P18-3", Location = "F16 | E18" },
                new CircuitBreaker() { System = "Hot Bat Bus", Panel = "P6-5", Location = "B3" },
                new CircuitBreaker() { System = "HUD Sys. Altn DC", Panel = "P18-2", Location = "C1" },
                new CircuitBreaker() { System = "HUD, Cont", Panel = "P18-2", Location = "C2" },
                new CircuitBreaker() { System = "HUD Sys, Normal DC", Panel = "P18-2", Location = "C3" },
                new CircuitBreaker() { System = "Hydraulic, Brake Press Ind", Panel = "P6-2", Location = "A13" },
                new CircuitBreaker() { System = "Hydraulic, Landing Gear Xfer Valve, Primary", Panel = "P6-2", Location = "C16" },
                new CircuitBreaker() { System = "Hydraulic, Landing Gear Xfer Valve, Secondary", Panel = "P6-2", Location = "C15" },
                new CircuitBreaker() { System = "Hydraulic, PTU Valve, Cont 1", Panel = "P6-2", Location = "A15" },
                new CircuitBreaker() { System = "Hydraulic, PTU Valve, Cont 2", Panel = "P6-2", Location = "A16" },
                new CircuitBreaker() { System = "Hydraulic Pump, Sys A", Panel = "P92", Location = "F3" },
                new CircuitBreaker() { System = "Hydraulic Pump, Sys B", Panel = "P91", Location = "F3" },
                new CircuitBreaker() { System = "Hydraulic Eng Pump Depress Valve 1", Panel = "P6-2", Location = "B15" },
                new CircuitBreaker() { System = "Hydraulic Eng Pump Depress Valve 2", Panel = "P6-2", Location = "A17" },
                new CircuitBreaker() { System = "Hydraulic, Electric Pump Cont Sys A", Panel = "P92", Location = "C8" },
                new CircuitBreaker() { System = "Hydraulic, Electric Pump Cont Sys B", Panel = "P91", Location = "C8" },
                new CircuitBreaker() { System = "Hydraulic Shutoff Valve, Eng 1", Panel = "P6-2", Location = "C19" },
                new CircuitBreaker() { System = "Hydraulic Shutoff Valve, Eng 2", Panel = "P6-2", Location = "C18" },
                new CircuitBreaker() { System = "Ignition, Engine 1, Left", Panel = "P18-2", Location = "A3" },
                new CircuitBreaker() { System = "Ignition, Engine 1, Right", Panel = "P18-2", Location = "A1" },
                new CircuitBreaker() { System = "Ignition, Engine 2, Left", Panel = "P6-2", Location = "D6" },
                new CircuitBreaker() { System = "Ignition, Engine 2, Right", Panel = "P6-2", Location = "D4" },
                new CircuitBreaker() { System = "ILS 1", Panel = "P18-1", Location = "A2" },
                new CircuitBreaker() { System = "ILS 2", Panel = "P6-1", Location = "A13" },
                new CircuitBreaker() { System = "Instrument Transfer", Panel = "P18-2", Location = "A2 & E2" },
                new CircuitBreaker() { System = "Instrument Transformer 1", Panel = "P18-2", Location = "A1" },
                new CircuitBreaker() { System = "Instrument Transformer 2", Panel = "P6-1", Location = "A12" },
                new CircuitBreaker() { System = "Interphone and Warning", Panel = "P6-2", Location = "D21" },
                new CircuitBreaker() { System = "Interphone Power, Capt DC2", Panel = "P6-2", Location = "C23" },
                new CircuitBreaker() { System = "Interphone Power, Capt Bat", Panel = "P6-2", Location = "C24" },
                new CircuitBreaker() { System = "Interphone Power, F/O DC2", Panel = "P6-2", Location = "C21" },
                new CircuitBreaker() { System = "Interphone Power, F/O Bat", Panel = "P6-2", Location = "C22" },
                new CircuitBreaker() { System = "Inverter, Remote (RCCB)", Panel = "P6-5", Location = "A5" },
                new CircuitBreaker() { System = "Inverter, Volts", Panel = "P6-5", Location = "A2" },
                new CircuitBreaker() { System = "ISFD", Panel = "", Location = "" },
                new CircuitBreaker() { System = "Landing Gear, Air/Gnd Sys 1", Panel = "P6-3", Location = "C16" },
                new CircuitBreaker() { System = "Landing Gear, Air/Gnd Sys 2", Panel = "P6-3", Location = "C15" },
                new CircuitBreaker() { System = "Landing Gear, Air/Gnd Relay", Panel = "P6-3", Location = "D15" },
                new CircuitBreaker() { System = "Landing Gear, Altn Extend Sol", Panel = "P6-3", Location = "D16" },
                new CircuitBreaker() { System = "Landing Gear, Anti-Skid, Inboard", Panel = "P6-3", Location = "E16" },
                new CircuitBreaker() { System = "Landing Gear, Anti-Skid, Outboard", Panel = "P6-3", Location = "E18" },
                new CircuitBreaker() { System = "Landing Gear, Aural Warn", Panel = "P6-3", Location = "D18" },
                new CircuitBreaker() { System = "Landing Gear, Auto Brake Bite Cont 1", Panel = "P6-3", Location = "A18" },
                new CircuitBreaker() { System = "Landing Gear, Auto Brake Bite Cont 2", Panel = "P6-3", Location = "A16" },
                new CircuitBreaker() { System = "Landing Gear, Auto Brake, Bite", Panel = "P6-3", Location = "A17" },
                new CircuitBreaker() { System = "Landing Gear, Latch & Press Warn", Panel = "P6-3", Location = "B17" },
                new CircuitBreaker() { System = "Landing Gear, Nose Gear Steering", Panel = "P6-3", Location = "D17" },
                new CircuitBreaker() { System = "Landing Gear, Parking Brake", Panel = "P6-3", Location = "B16" },
                new CircuitBreaker() { System = "Landing Gear, Takeoff Warning Cutoff", Panel = "P6-3", Location = "C18" },
                new CircuitBreaker() { System = "Landing Gear Xfer Valve, Primary", Panel = "P6-2", Location = "C16" },
                new CircuitBreaker() { System = "Landing Gear Xfer Valve, Secondary", Panel = "P6-2", Location = "C15" },
                new CircuitBreaker() { System = "Lavatory Hose Heaters", Panel = "P18-3", Location = "F16" },
                new CircuitBreaker() { System = "Lavatory Occupied Sign", Panel = "P18-3", Location = "D9" },
                new CircuitBreaker() { System = "Lavatory Smoke Detector", Panel = "P18-3", Location = "E12" },
                new CircuitBreaker() { System = "Lavatory Water Heaters, A", Panel = "P18-3", Location = "F13" },
                new CircuitBreaker() { System = "Lavatory Water Heaters, B", Panel = "P18-3", Location = "F14" },
                new CircuitBreaker() { System = "Lavatory Water Heaters, C", Panel = "P18-3", Location = "F15" },
                new CircuitBreaker() { System = "Light, Access Comp", Panel = "P91", Location = "C5" },
                new CircuitBreaker() { System = "Light, Air Cond Comp", Panel = "P92", Location = "C3" },
                new CircuitBreaker() { System = "Light, Anti-Collision, Red", Panel = "P18-3", Location = "B12" },
                new CircuitBreaker() { System = "Light, Anti-Collision, White", Panel = "P18-3", Location = "B13" },
                new CircuitBreaker() { System = "Light, Auto Dim Entry", Panel = "P6-3", Location = "E10" },
                new CircuitBreaker() { System = "Light, Capt Panel (3)", Panel = "CA Rud Adj", Location = "" },
                new CircuitBreaker() { System = "Light, Cargo Compt Lt Aft", Panel = "P92", Location = "C5" },
                new CircuitBreaker() { System = "Light, Cargo Compt Lt Fwd", Panel = "P92", Location = "C4" },
                new CircuitBreaker() { System = "Light, Cargo Light Cont", Panel = "P92", Location = "C10" },
                new CircuitBreaker() { System = "Light, Ceiling, Right", Panel = "P91", Location = "D11" },
                new CircuitBreaker() { System = "Light, Center Console Panel, Fwd, Capt, Centr, F/P", Panel = "Aft Console", Location = "" },
                new CircuitBreaker() { System = "Light, Center Panel (2)", Panel = "CA Rud Adj", Location = "" },
                new CircuitBreaker() { System = "Light, Circuit Breaker Panel", Panel = "P6-3", Location = "C9" },
                new CircuitBreaker() { System = "Light, Compass, Standby", Panel = "P6-3", Location = "A13" },
                new CircuitBreaker() { System = "Light, Cont 1", Panel = "P6-3", Location = "C11" },
                new CircuitBreaker() { System = "Light, Cont 2", Panel = "P6-3", Location = "C12" },
                new CircuitBreaker() { System = "Light, Cont 3", Panel = "P6-3", Location = "C13" },
                new CircuitBreaker() { System = "Light, Cont 4", Panel = "P6-3", Location = "C14" },
                new CircuitBreaker() { System = "Light, Control Stand", Panel = "P6-3", Location = "A8" },
                new CircuitBreaker() { System = "Light, Dome White", Panel = "P6-3", Location = "A15" },
                new CircuitBreaker() { System = "Light, Elec Rack, Fwd", Panel = "P91", Location = "C2" },
                new CircuitBreaker() { System = "Light, Elec Panel", Panel = "P6-3", Location = "C10" },
                new CircuitBreaker() { System = "Light, Emer and F/O's Panel (5)", Panel = "F/O Rud Adj", Location = "" },
                new CircuitBreaker() { System = "Light, Emer Chgr, Fwd", Panel = "P18-3", Location = "A11" },
                new CircuitBreaker() { System = "Light, Emer Chgr, Left Aft", Panel = "P18-3", Location = "A10" },
                new CircuitBreaker() { System = "Light, Emer Chgr, Right Aft", Panel = "P18-3", Location = "B10" },
                new CircuitBreaker() { System = "Light, Emer Panel", Panel = "P6-3", Location = "D8" },
                new CircuitBreaker() { System = "Light, Entry Brt", Panel = "P91", Location = "E10" },
                new CircuitBreaker() { System = "Light, Entry Dim", Panel = "P6-4", Location = "E9" },
                new CircuitBreaker() { System = "Light, Galley", Panel = "P18-3", Location = "B10" },
                new CircuitBreaker() { System = "Light, Galley", Panel = "P92", Location = "E10" },
                new CircuitBreaker() { System = "Light, General Light Cont", Panel = "P18-3", Location = "D12" },
                new CircuitBreaker() { System = "Light, Gnd Serv Clg Night Cont", Panel = "P91", Location = "C4" },
                new CircuitBreaker() { System = "Light, Gnd Serv Wdo Brt Cont", Panel = "P6-3", Location = "D12" },
                new CircuitBreaker() { System = "Light, Indicator Master Dim, Bat", Panel = "P6-3", Location = "D12" },
                new CircuitBreaker() { System = "Light, Indicator, Master Dim, DC 1", Panel = "P6-3", Location = "D13" },
                new CircuitBreaker() { System = "Light, Indicator, Master Dim, DC 2", Panel = "P6-3", Location = "D14" },
                new CircuitBreaker() { System = "Light, Indicator, Master Dim, Dim/Test Cont", Panel = "P6-3", Location = "D11" },
                new CircuitBreaker() { System = "Light, Indicator, Master Dim, Sect 1", Panel = "P6-3", Location = "E11" },
                new CircuitBreaker() { System = "Light, Indicator, Master Dim, Sect 2", Panel = "P6-3", Location = "E12" },
                new CircuitBreaker() { System = "Light, Indicator, Master Dim, Sect 3", Panel = "P6-3", Location = "E13" },
                new CircuitBreaker() { System = "Light, Indicator, Master Dim, Sect 4", Panel = "P6-3", Location = "E14" },
                new CircuitBreaker() { System = "Light, Indicator, Master Dim, Sect 5", Panel = "P6-3", Location = "F11" },
                new CircuitBreaker() { System = "Light, Indicator, Master Dim, Sect 6", Panel = "P6-3", Location = "F12" },
                new CircuitBreaker() { System = "Light, Indicator, Master Dim, Sect 7", Panel = "P6-3", Location = "F13" },
                new CircuitBreaker() { System = "Light, Indicator, Master Dim, Sect 8", Panel = "P6-3", Location = "F14" },
                new CircuitBreaker() { System = "Light, Landing, Left Fixed", Panel = "P18-3", Location = "B15" },
                new CircuitBreaker() { System = "Light, Landing, Left Retractable", Panel = "P18-3", Location = "C15" },
                new CircuitBreaker() { System = "Light, Landing, Right Fixed", Panel = "P18-3", Location = "C14" },
                new CircuitBreaker() { System = "Light, Landing, Right Retractable", Panel = "P18-3", Location = "B14" },
                new CircuitBreaker() { System = "Light, Lavatory Mirror", Panel = "P18-3", Location = "E14" },
                new CircuitBreaker() { System = "Light, Lav Occupied Sign", Panel = "P18-3", Location = "D9" },
                new CircuitBreaker() { System = "Light, LCD", Panel = "P6-4", Location = "F1" },
                new CircuitBreaker() { System = "Light, Logo, Illum", Panel = "P18-3", Location = "A15" },
                new CircuitBreaker() { System = "Light, Map & Kit", Panel = "P6-3", Location = "A9" },
                new CircuitBreaker() { System = "Light, Nose Gear Taxi", Panel = "P18-3", Location = "D14" },
                new CircuitBreaker() { System = "Light, Observer Reading", Panel = "P6-3", Location = "A10" },
                new CircuitBreaker() { System = "Light, Overhead, 28V Primary", Panel = "P6-3", Location = "D9" },
                new CircuitBreaker() { System = "Light, Overhead, 28V Secondary", Panel = "P6-3", Location = "D10" },
                new CircuitBreaker() { System = "Light, Overhead, 5V Secondary", Panel = "P6-3", Location = "E8" },
                new CircuitBreaker() { System = "Light, Overhead, 5V Secondary", Panel = "P6-3", Location = "E9" },
                new CircuitBreaker() { System = "Light, Overhead, 5V Secondary", Panel = "P6-3", Location = "E10" },
                new CircuitBreaker() { System = "Light, Overhead, 5V Secondary", Panel = "P6-3", Location = "F8" },
                new CircuitBreaker() { System = "Light, Overhead, 5V Secondary", Panel = "P6-3", Location = "F9" },
                new CircuitBreaker() { System = "Light, Overhead, 5V Secondary", Panel = "P6-3", Location = "F10" },
                new CircuitBreaker() { System = "Light, Panel & Instr, 28V Primary, Capt & Ctr", Panel = "P6-3", Location = "B9" },
                new CircuitBreaker() { System = "Light, Panel & Instr, 28V Primary, F/O", Panel = "P6-3", Location = "B10" },
                new CircuitBreaker() { System = "Light, Panel & Instr, CB Panel", Panel = "P6-3", Location = "C9" },
                new CircuitBreaker() { System = "Light, Panel & Instr, Elex Panel", Panel = "P6-3", Location = "C10" },
                new CircuitBreaker() { System = "Light, Panel Flood Cont", Panel = "P6-3", Location = "A11" },
                new CircuitBreaker() { System = "Light, Panel Flood Stby", Panel = "P6-3", Location = "A12" },
                new CircuitBreaker() { System = "Light, Passenger Reading, Right, Sta 340-451", Panel = "P92", Location = "B1" },
                new CircuitBreaker() { System = "Light, Passenger Reading, Right, Sta 451-500E", Panel = "P92", Location = "B2" },
                new CircuitBreaker() { System = "Light, Passenger Reading, Right, Sta 500E-552", Panel = "P92", Location = "B3" },
                new CircuitBreaker() { System = "Light, Passenger Reading, Right, Sta 552-692", Panel = "P92", Location = "B4" },
                new CircuitBreaker() { System = "Light, Passenger Reading, Right, Sta 692-727B", Panel = "P92", Location = "B5" },
                new CircuitBreaker() { System = "Light, Passenger Reading, Right, Sta 727B-727G", Panel = "P92", Location = "B6" },
                new CircuitBreaker() { System = "Light, Passenger Reading, Right, Sta 727G-768", Panel = "P92", Location = "B7" },
                new CircuitBreaker() { System = "Light, Passenger Reading, Right, Sta 768-880", Panel = "P92", Location = "B8" },
                new CircuitBreaker() { System = "Light, Passenger Reading, Right, Sta 880-937", Panel = "P92", Location = "B9" },
                new CircuitBreaker() { System = "Light, Passenger Reading, Left, Sta 340-451", Panel = "P91", Location = "B1" },
                new CircuitBreaker() { System = "Light, Passenger Reading, Left, Sta 451-500E", Panel = "P91", Location = "B2" },
                new CircuitBreaker() { System = "Light, Passenger Reading, Left, Sta 500E-552", Panel = "P91", Location = "B3" },
                new CircuitBreaker() { System = "Light, Passenger Reading, Left, Sta 552-692", Panel = "P91", Location = "B4" },
                new CircuitBreaker() { System = "Light, Passenger Reading, Left, Sta 692-727B", Panel = "P91", Location = "B5" },
                new CircuitBreaker() { System = "Light, Passenger Reading, Left, Sta 727B-727G", Panel = "P91", Location = "B6" },
                new CircuitBreaker() { System = "Light, Passenger Reading, Left, Sta 727G-768", Panel = "P91", Location = "B7" },
                new CircuitBreaker() { System = "Light, Passenger Reading, Left, Sta 768-880", Panel = "P91", Location = "B8" },
                new CircuitBreaker() { System = "Light, Passenger Reading, Left, Sta 880-937", Panel = "P91", Location = "B9" },
                new CircuitBreaker() { System = "Light, Position, Left", Panel = "P18-3", Location = "A13" },
                new CircuitBreaker() { System = "Light, Position, Right", Panel = "P18-3", Location = "A12" },
                new CircuitBreaker() { System = "Light, Runway Turnoff, Leff", Panel = "P18-3", Location = "C13" },
                new CircuitBreaker() { System = "Light, Runway Turnoff, Right", Panel = "P18-3", Location = "C12" },
                new CircuitBreaker() { System = "Light, Sect 1", Panel = "P6-3", Location = "E11" },
                new CircuitBreaker() { System = "Light, Sect 2", Panel = "P6-3", Location = "E12" },
                new CircuitBreaker() { System = "Light, Sect 3", Panel = "P6-3", Location = "E13" },
                new CircuitBreaker() { System = "Light, Sect 4", Panel = "P6-3", Location = "E14" },
                new CircuitBreaker() { System = "Light, Sect 5", Panel = "P6-3", Location = "F11" },
                new CircuitBreaker() { System = "Light, Sect 6", Panel = "P6-3", Location = "F12" },
                new CircuitBreaker() { System = "Light, Sect 7", Panel = "P6-3", Location = "F13" },
                new CircuitBreaker() { System = "Light, Sect 6", Panel = "P6-3", Location = "F14" },
                new CircuitBreaker() { System = "Light, Stby Compass", Panel = "P6-3", Location = "A14" },
                new CircuitBreaker() { System = "Light, Thrsh", Panel = "P91", Location = "C1" },
                new CircuitBreaker() { System = "Light, WDO, Left", Panel = "P92", Location = "E12" },
                new CircuitBreaker() { System = "Light, WDO, Right", Panel = "P92", Location = "E11" },
                new CircuitBreaker() { System = "Light, Wheel well", Panel = "P92", Location = "C2" },
                new CircuitBreaker() { System = "Light, Window, Left", Panel = "P92", Location = "E12" },
                new CircuitBreaker() { System = "Light, Window, Right", Panel = "P92", Location = "E11" },
                new CircuitBreaker() { System = "Light, Wing Scan", Panel = "P18-3", Location = "A14" },
                new CircuitBreaker() { System = "Light, Work and Thrsh", Panel = "P91", Location = "C3" },
                new CircuitBreaker() { System = "Mach Trim, AC Sys A", Panel = "P18-1", Location = "C4" },
                new CircuitBreaker() { System = "Mach Trim, DC Sys A", Panel = "P18-1", Location = "D4" },
                new CircuitBreaker() { System = "Mach Trim, AC Sys B", Panel = "P6-2", Location = "C1" },
                new CircuitBreaker() { System = "Mach Trim, AC Sys B", Panel = "P6-2", Location = "B2" },
                new CircuitBreaker() { System = "Mach Warn Sys 1", Panel = "P18-2", Location = "E3" },
                new CircuitBreaker() { System = "Mach Warn Sys 2", Panel = "P6-1", Location = "B7" },
                new CircuitBreaker() { System = "Main Bus 1", Panel = "P91", Location = "F6" },
                new CircuitBreaker() { System = "Main Bus 2", Panel = "P92", Location = "F6" },
                new CircuitBreaker() { System = "Marker Beaco 2", Panel = "P6-1", Location = "A13" },
                new CircuitBreaker() { System = "Master Caution, Annunciator Bus 1", Panel = "P6-3", Location = "B12" },
                new CircuitBreaker() { System = "Master Caution, Annunciator Bat", Panel = "P6-3", Location = "B13" },
                new CircuitBreaker() { System = "Master Caution, Annunciator Cont 1", Panel = "P6-3", Location = "C11" },
                new CircuitBreaker() { System = "Master Caution, Annunciator Cont 2", Panel = "P6-3", Location = "C12" },
                new CircuitBreaker() { System = "Master Caution, Annunciator Cont 3", Panel = "P6-3", Location = "C13" },
                new CircuitBreaker() { System = "Master Caution, Annunciator Cont 4", Panel = "P6-3", Location = "C14" },
                new CircuitBreaker() { System = "MCP DC 1", Panel = "P18-1", Location = "D5" },
                new CircuitBreaker() { System = "MCP DC 2", Panel = "P6-2", Location = "P6-2" },
                new CircuitBreaker() { System = "MIDU", Panel = "P6-3", Location = "A1" },
                new CircuitBreaker() { System = "MMR 1 (GPS 1)", Panel = "P18-1", Location = "A2" },
                new CircuitBreaker() { System = "MMR 2 (GPS 2)", Panel = "P6-1", Location = "A13" },
                new CircuitBreaker() { System = "MPES MK II, Aeris Fx", Panel = "P6-1", Location = "C8" },
                new CircuitBreaker() { System = "MPES MK II, Main Mux", Panel = "P6-1", Location = "C7" },
                new CircuitBreaker() { System = "MPES MK II, VCC 28 vac", Panel = "P6-1", Location = "C9" },
                new CircuitBreaker() { System = "MPES MK II, VCC 115 vac", Panel = "P6-1", Location = "C10" },
                new CircuitBreaker() { System = "MPES MK II, VDU 1-4", Panel = "P6-1", Location = "C11" },
                new CircuitBreaker() { System = "MPES MK II, VDU 5-7", Panel = "P6-1", Location = "C12" },
                new CircuitBreaker() { System = "MPES MK II, VDU 8-10", Panel = "P6-1", Location = "C13" },
                new CircuitBreaker() { System = "Nav Control Panel 1", Panel = "P18-1", Location = "A3" },
                new CircuitBreaker() { System = "Nav Control Panel 2", Panel = "P6-1", Location = "A15" },
                new CircuitBreaker() { System = "Nav Sensor DC-1", Panel = "P18-1", Location = "B1" },
                new CircuitBreaker() { System = "Nav Sensor DC-2", Panel = "P6-1", Location = "A10" },
                new CircuitBreaker() { System = "No Smoking, Left", Panel = "P18-3", Location = "C11" },
                new CircuitBreaker() { System = "No Smoking, Right", Panel = "P18-3", Location = "C10" },
                new CircuitBreaker() { System = "OPC/Laptop", Panel = "P18-3", Location = "F5" },
                new CircuitBreaker() { System = "Overboard Exhaust Valve, Cont", Panel = "P6-4", Location = "D1" },
                new CircuitBreaker() { System = "Overboard Exhaust Valve, Reconfig Cont", Panel = "P6-4", Location = "D2" },
                new CircuitBreaker() { System = "Overwing Flight Lock, Left", Panel = "P6-2", Location = "D2" },
                new CircuitBreaker() { System = "Overwing Flight Lock, Right", Panel = "P6-2", Location = "D1" },
                new CircuitBreaker() { System = "Overheat, Wheel Well, Wing-Body", Panel = "P6-2", Location = "A19" },
                new CircuitBreaker() { System = "Oxygen, Indicator", Panel = "P18-3", Location = "F7" },
                new CircuitBreaker() { System = "Oxygen, Manual Control", Panel = "P18-3", Location = "F8" },
                new CircuitBreaker() { System = "Oxygen, Pass Left", Panel = "P18-3", Location = "F10" },
                new CircuitBreaker() { System = "Oxygen, Pass Right", Panel = "P18-3", Location = "F9" },
                new CircuitBreaker() { System = "PA Amp, Bat", Panel = "P6-1", Location = "D4" },
                new CircuitBreaker() { System = "Pack Controller, Left Electronic (8-9)", Panel = "P6-4", Location = "A9" },
                new CircuitBreaker() { System = "Pack Controller, Left Electronic (8-9)", Panel = "P6-4", Location = "A11" },
                new CircuitBreaker() { System = "Pack Controller, Right Electronic (8-9)", Panel = "P6-4", Location = "B9" },
                new CircuitBreaker() { System = "Pack Controller, Right Electronic (8-9)", Panel = "P6-4", Location = "B11" },
                new CircuitBreaker() { System = "Pack Cont Valve, Left", Panel = "P6-4", Location = "C6" },
                new CircuitBreaker() { System = "Pack Cont Valve, Right", Panel = "P6-4", Location = "C5" },
                new CircuitBreaker() { System = "Parking Brake", Panel = "P6-3", Location = "B16" },
                new CircuitBreaker() { System = "Pass Telephone (NATS)", Panel = "P6-1", Location = "E2" },
                new CircuitBreaker() { System = "Passenger Call Right", Panel = "P18-3", Location = "B8" },
                new CircuitBreaker() { System = "Passenger Call Left", Panel = "P18-3", Location = "A8" },
                new CircuitBreaker() { System = "Passenger Crew Call", Panel = "P18-3", Location = "A9" },
                new CircuitBreaker() { System = "Passenger Sign Cont", Panel = "P18-3", Location = "D11" },
                new CircuitBreaker() { System = "PC Power, Y/C", Panel = "P6-12", Location = "A8" },
                new CircuitBreaker() { System = "PC Power, F/C", Panel = "P6-12", Location = "A5" },
                new CircuitBreaker() { System = "Pot Water Compressor", Panel = "P91", Location = "A18" },
                new CircuitBreaker() { System = "Pressurization Control, Auto 1", Panel = "P6-4", Location = "F3" },
                new CircuitBreaker() { System = "Pressurization Control, Auto 2", Panel = "P6-4", Location = "F5" },
                new CircuitBreaker() { System = "Pressurization Control, Ind", Panel = "P6-4", Location = "F7" },
                new CircuitBreaker() { System = "Pressurization Control, Manual", Panel = "P6-4", Location = "F6" },
                new CircuitBreaker() { System = "Pressurization LCD Ltg", Panel = "P6-4", Location = "F1" },
                new CircuitBreaker() { System = "PRTR (Printer)", Panel = "P6-3", Location = "E5" },
                new CircuitBreaker() { System = "Probe, Indication, Capt", Panel = "P6-3", Location = "F18" },
                new CircuitBreaker() { System = "Probe, Indication, F/O", Panel = "P6-3", Location = "F16" },
                new CircuitBreaker() { System = "PSEU, Altn", Panel = "P6-3", Location = "D2" },
                new CircuitBreaker() { System = "PSEU, DC 1", Panel = "P6-2", Location = "A8" },
                new CircuitBreaker() { System = "PSEU, DC 2", Panel = "P6-2", Location = "A9" },
                new CircuitBreaker() { System = "PSEU, Primary", Panel = "P6-3", Location = "D1" },
                new CircuitBreaker() { System = "PTU Valve, Cont 1", Panel = "P6-2", Location = "A15" },
                new CircuitBreaker() { System = "PTU Valve, Cont 2", Panel = "P6-2", Location = "A16" },
                new CircuitBreaker() { System = "Radio Altim 1", Panel = "P18-1", Location = "B4" },
                new CircuitBreaker() { System = "Radio Altim 2", Panel = "P6-1", Location = "A16" },
                new CircuitBreaker() { System = "Ram Air Mod Cont, Left", Panel = "P6-4", Location = "A8" },
                new CircuitBreaker() { System = "Ram Air Mod Cont, Right", Panel = "P6-4", Location = "B8" },
                new CircuitBreaker() { System = "Ram Air Mod, Left", Panel = "P6-4", Location = "A4" },
                new CircuitBreaker() { System = "Ram Air Mod, Right", Panel = "P6-4", Location = "B4" },
                new CircuitBreaker() { System = "RCCB, Remote (inverter)", Panel = "P6-5", Location = "A4" },
                new CircuitBreaker() { System = "Recirc Fan, Cabin", Panel = "P6-4", Location = "E4" },
                new CircuitBreaker() { System = "Recirc Fan, Left Cabin Air (8-9)", Panel = "P18-3", Location = "E7" },
                new CircuitBreaker() { System = "Recirc Fan, Right Cabin Air (8-9)", Panel = "P6-4", Location = "E4" },
                new CircuitBreaker() { System = "Recirc Fan, Control", Panel = "P6-4", Location = "E1" },
                new CircuitBreaker() { System = "Recirc Fan, Left Control (8-9)", Panel = "P18-3", Location = "E9" },
                new CircuitBreaker() { System = "Recirc Fan, Right Control (8-9)", Panel = "P6-4", Location = "E2" },
                new CircuitBreaker() { System = "RMI 1", Panel = "P18-1", Location = "A5" },
                new CircuitBreaker() { System = "Rudder Authority Limiter", Panel = "P6-2", Location = "C9" },
                new CircuitBreaker() { System = "Rudder Trim Indicator", Panel = "P6-2", Location = "D16" },
                new CircuitBreaker() { System = "Run/Pwr, Eng 1", Panel = "P18-2", Location = "B3" },
                new CircuitBreaker() { System = "Run/Pwr, Eng 2", Panel = "P6-2", Location = "B5" },
                new CircuitBreaker() { System = "SELCAL 1", Panel = "P18-2", Location = "D15" },
                new CircuitBreaker() { System = "Sensor Exc, AC, AFCS Sys A", Panel = "P18-1", Location = "C5" },
                new CircuitBreaker() { System = "Service Outlet, 28V DC", Panel = "P6-3", Location = "F1" },
                new CircuitBreaker() { System = "Service Outlet", Panel = "P92", Location = "E7" },
                new CircuitBreaker() { System = "Shaver Outlet, 115V AC", Panel = "P18-3", Location = "F12" },
                new CircuitBreaker() { System = "SMYD-1, Computer DC", Panel = "P18-2", Location = "E5" },
                new CircuitBreaker() { System = "SMYD-2, Computer DC", Panel = "P6-1", Location = "B5" },
                new CircuitBreaker() { System = "SMYD-1, Sensor EXC AC", Panel = "P18-2", Location = "E6" },
                new CircuitBreaker() { System = "SMYD-2, Sensor EXC AC", Panel = "P6-2", Location = "B4" },
                new CircuitBreaker() { System = "SPCU, Normal", Panel = "P6-5", Location = "B1" },
                new CircuitBreaker() { System = "SPCU, Standby", Panel = "P6-5", Location = "B2" },
                new CircuitBreaker() { System = "Spoiler Shutoff Valve", Panel = "P6-2", Location = "B12" },
                new CircuitBreaker() { System = "Stabilizer Trim", Panel = "P18-1", Location = "C2" },
                new CircuitBreaker() { System = "Stab Trim Actuator", Panel = "P6-2", Location = "D10" },
                new CircuitBreaker() { System = "Stab Trim Control", Panel = "P6-2", Location = "B10" },
                new CircuitBreaker() { System = "Stall Warn, Asym Mode", Panel = "P18-2", Location = "E7" },
                new CircuitBreaker() { System = "Standby Altm/ASI Vib", Panel = "P18-2", Location = "D10" },
                new CircuitBreaker() { System = "Standby Att Ind", Panel = "P18-2", Location = "D9" },
                new CircuitBreaker() { System = "Standby Bus, 28V AC Dist", Panel = "P6-4", Location = "D15" },
                new CircuitBreaker() { System = "Standby Bus, 115V AC Ind", Panel = "P6-4", Location = "D16" },
                new CircuitBreaker() { System = "Standby Bus, Sect 1", Panel = "P6-5", Location = "C1" },
                new CircuitBreaker() { System = "Standby Bus, Sect 2", Panel = "P6-5", Location = "C2" },
                new CircuitBreaker() { System = "Standby Hydraulic Pump", Panel = "P92", Location = "F2" },
                new CircuitBreaker() { System = "Start Lever, Eng 1, Channel A", Panel = "P18-2", Location = "B1" },
                new CircuitBreaker() { System = "Start Lever, Eng 2, Channel B", Panel = "P18-2", Location = "B2" },
                new CircuitBreaker() { System = "Start Lever, Eng 2, Channel A", Panel = "P6-2", Location = "B6" },
                new CircuitBreaker() { System = "Start Lever, Eng 2, Channel B", Panel = "P6-2", Location = "B7" },
                new CircuitBreaker() { System = "Start Valve Eng 1", Panel = "P18-2", Location = "B8" },
                new CircuitBreaker() { System = "Start Valve Eng 2", Panel = "P6-2", Location = "C4" },
                new CircuitBreaker() { System = "Stick Shaker, Left", Panel = "P18-2", Location = "E4" },
                new CircuitBreaker() { System = "Stick Shaker, Right", Panel = "P6-1", Location = "B6" },
                new CircuitBreaker() { System = "Switched Hot Batt Bus", Panel = "P6-5", Location = "B4" },
                new CircuitBreaker() { System = "Takeoff Warning Cutoff", Panel = "P6-3", Location = "C18" },
                new CircuitBreaker() { System = "TCAS", Panel = "P18-1", Location = "B6" },
                new CircuitBreaker() { System = "Temp Control, 35°F Left (6-7)", Panel = "P6-4", Location = "A1" },
                new CircuitBreaker() { System = "Temp Control, 35°F Right (6-7)", Panel = "P6-4", Location = "B1" },
                new CircuitBreaker() { System = "Temp Control, Auto Left (6-7)", Panel = "P6-4", Location = "A2" },
                new CircuitBreaker() { System = "Temp Control, Auto Right (6-7)", Panel = "P6-4", Location = "B2" },
                new CircuitBreaker() { System = "Temp Control, Manual (6-7)", Panel = "P6-4", Location = "A3" },
                new CircuitBreaker() { System = "Temp Control, Valve Close Left (8-9)", Panel = "P6-4", Location = "A1" },
                new CircuitBreaker() { System = "Temp Control, Valve Close Right (8-9)", Panel = "P6-4", Location = "B1" },
                new CircuitBreaker() { System = "Temperature Ind (6-7)", Panel = "P6-4", Location = "D2" },
                new CircuitBreaker() { System = "Terrain Display", Panel = "P18-1", Location = "A7" },
                new CircuitBreaker() { System = "Thrust Reverser, Cont, Engine 1", Panel = "P18-2", Location = "B5" },
                new CircuitBreaker() { System = "Thrust Reverser, Cont, Engine 2", Panel = "P6-2", Location = "C7" },
                new CircuitBreaker() { System = "Thrust Reverser, Ind, Engine 1", Panel = "P18-2", Location = "B4" },
                new CircuitBreaker() { System = "Thrust Reverser, Ind, Engine 2", Panel = "P6-2", Location = "C8" },
                new CircuitBreaker() { System = "Thrust Reverser, Interlock, Engine 1", Panel = "P18-2", Location = "B6" },
                new CircuitBreaker() { System = "Thrust Reverser, Sync Lock, Engine 1", Panel = "P18-2", Location = "B7" },
                new CircuitBreaker() { System = "Thrust Reverser, Interlock, Engine 2", Panel = "P6-2", Location = "C6" },
                new CircuitBreaker() { System = "Thrust Reverser, Sync Lock, Engine 2", Panel = "P6-2", Location = "B5" },
                new CircuitBreaker() { System = "Total Air Temperature Indicator", Panel = "P18-2", Location = "A7" },
                new CircuitBreaker() { System = "TR1", Panel = "P91", Location = "A6" },
                new CircuitBreaker() { System = "TR3 Altn", Panel = "P91", Location = "A4" },
                new CircuitBreaker() { System = "TR3, DC Indicator", Panel = "P6-5", Location = "C3" },
                new CircuitBreaker() { System = "TR3 Xfer Relay Cont", Panel = "P6-4", Location = "E11" },
                new CircuitBreaker() { System = "Trailing Edge Flap Position Skew Snsr & Ind, Rt", Panel = "P6-2", Location = "A11" },
                new CircuitBreaker() { System = "Trailing Edge Flap Position Skew Snsr & Ind, Lt", Panel = "P6-2", Location = "A12" },
                new CircuitBreaker() { System = "Transfer Bus 1 Sect 2, 28V AC", Panel = "P18-3", Location = "C5" },
                new CircuitBreaker() { System = "Transfer Bus 1, 28V AC", Panel = "P91", Location = "B10" },
                new CircuitBreaker() { System = "Transfer Bus 2, 28V AC", Panel = "P92", Location = "B10" },
                new CircuitBreaker() { System = "Transfer Bus 2, 115V AC Ind", Panel = "P6-4", Location = "D13" },
                new CircuitBreaker() { System = "Transfer Bus 2, Sect 2, 28V AC", Panel = "P6-4", Location = "D14" },
                new CircuitBreaker() { System = "Trim Air Press (800)", Panel = "P6-4", Location = "D9" },
                new CircuitBreaker() { System = "Trim Control, Aileron", Panel = "P6-2", Location = "D18" },
                new CircuitBreaker() { System = "Trim Control, Rudder", Panel = "P6-2", Location = "D19" },
                new CircuitBreaker() { System = "TRU 1", Panel = "P91", Location = "A6" },
                new CircuitBreaker() { System = "TRU 2", Panel = "P92", Location = "A4" },
                new CircuitBreaker() { System = "TRU 3", Panel = "P92", Location = "A6" },
                new CircuitBreaker() { System = "TRU 3 Altn", Panel = "P91", Location = "A4" },
                new CircuitBreaker() { System = "Vacuum Outlet, Aft", Panel = "P92", Location = "E9" },
                new CircuitBreaker() { System = "Vacuum Outlet, Fwd", Panel = "P92", Location = "E8" },
                new CircuitBreaker() { System = "Vacuum Waste Ind", Panel = "P18-3", Location = "D19" },
                new CircuitBreaker() { System = "Vacuum Waste Blower", Panel = "P91", Location = "F2" },
                new CircuitBreaker() { System = "Vacuum Wast Cont", Panel = "P91", Location = "C11" },
                new CircuitBreaker() { System = "VHF 1", Panel = "P18-2", Location = "D11" },
                new CircuitBreaker() { System = "VHF 2", Panel = "P6-1", Location = "C3" },
                new CircuitBreaker() { System = "VHF 3", Panel = "P18-2", Location = "D12" },
                new CircuitBreaker() { System = "VID Cont Center AC", Panel = "P6-1", Location = "C7" },
                new CircuitBreaker() { System = "VID Cont Center AC", Panel = "P6-1", Location = "C5" },
                new CircuitBreaker() { System = "Video 1", Panel = "P6-1", Location = "D5" },
                new CircuitBreaker() { System = "Video 2", Panel = "P6-1", Location = "D6" },
                new CircuitBreaker() { System = "Video 3", Panel = "P6-1", Location = "D7" },
                new CircuitBreaker() { System = "Video 4", Panel = "P6-1", Location = "D8" },
                new CircuitBreaker() { System = "Voice Recorder", Panel = "P18-2", Location = "D7" },
                new CircuitBreaker() { System = "VOR / MKR Beacon 1", Panel = "P18-1", Location = "A1" },
                new CircuitBreaker() { System = "VOR 2", Panel = "P6-1", Location = "A12" },
                new CircuitBreaker() { System = "Waste, Water Line Heaters", Panel = "P18-3", Location = "D18" },
                new CircuitBreaker() { System = "Water Drain Valve, Grey", Panel = "P18-3", Location = "E19" },
                new CircuitBreaker() { System = "Water Qty Ind", Panel = "P91", Location = "C9" },
                new CircuitBreaker() { System = "Weather Radar, R/T", Panel = "P6-1", Location = "D13" },
                new CircuitBreaker() { System = "Window Heat Control, Left Front AC", Panel = "P18-3", Location = "E1" },
                new CircuitBreaker() { System = "Window Heat Control, Left Front DC", Panel = "P18-3", Location = "F2" },
                new CircuitBreaker() { System = "Window Heat Control, Left Side AC", Panel = "P18-3", Location = "D2" },
                new CircuitBreaker() { System = "Window Heat Control, Left Side DC", Panel = "P18-3", Location = "D2" },
                new CircuitBreaker() { System = "Window Heat Control, Right Front AC", Panel = "P18-3", Location = "D1" },
                new CircuitBreaker() { System = "Window Heat Control, Right Front DC", Panel = "P18-3", Location = "E2" },
                new CircuitBreaker() { System = "Window Heat Control, Right Side AC", Panel = "P18-3", Location = "E2" },
                new CircuitBreaker() { System = "Window Heat Control, Right Side DC", Panel = "P18-3", Location = "E2" },
                new CircuitBreaker() { System = "Window Heat Power, Left Front", Panel = "P6-11", Location = "B9" },
                new CircuitBreaker() { System = "Window Heat Power, Left Side", Panel = "P6-12", Location = "A9" },
                new CircuitBreaker() { System = "Window Heat Power, L4 & L5", Panel = "P6-11", Location = "B7" },
                new CircuitBreaker() { System = "Window Heat Power, Right Front", Panel = "P6-12", Location = "A8" },
                new CircuitBreaker() { System = "Window Heat Power, R4 & R5", Panel = "P6-12", Location = "A7" },
                new CircuitBreaker() { System = "Windshield Wiper, Left", Panel = "P18-3", Location = "B3" },
                new CircuitBreaker() { System = "Windshield Wiper, Right", Panel = "P18-3", Location = "B1" },
                new CircuitBreaker() { System = "Wing Anti-Ice Valve", Panel = "P18-3", Location = "A1" },
                new CircuitBreaker() { System = "Xfer Bus 1 Sect 1", Panel = "P91", Location = "F4" },
                new CircuitBreaker() { System = "Xfer Bus 1 Sect 2", Panel = "P91", Location = "F5" },
                new CircuitBreaker() { System = "Xfer Bus 2 Sect 1", Panel = "P92", Location = "F4" },
                new CircuitBreaker() { System = "Xfer Bus 2 Sect 2", Panel = "P92", Location = "F5" },
                new CircuitBreaker() { System = "Yaw Damper AC", Panel = "P18-1", Location = "C7" },
                new CircuitBreaker() { System = "Yaw Damper 1 DC", Panel = "P18-1", Location = "D7" },
                new CircuitBreaker() { System = "Yaw Damper Indicator", Panel = "P18-1", Location = "C6" },
                new CircuitBreaker() { System = "Yaw Damper 2 DC", Panel = "P18-1", Location = "D6" },
                new CircuitBreaker() { System = "Zone Temp, Duct Ovht, Aft Pass (8-9)", Panel = "P6-4", Location = "C2" },
                new CircuitBreaker() { System = "Zone Temp, Duct Ovht, Fwd Pass (8-9)", Panel = "P6-4", Location = "C3" },
                new CircuitBreaker() { System = "Zone Temp, Duct Ovht, Flt Deck (8-9)", Panel = "P6-4", Location = "C4" }
            };
        }

        public List<CircuitBreaker> Search(string query)
        {
            if (!String.IsNullOrEmpty(query) && !String.IsNullOrWhiteSpace(query))
            {
                return new List<CircuitBreaker>
                (
                    from circuitBreaker in CircuitBreakerList where circuitBreaker.System.ToLower().Contains(query.ToLower()) select circuitBreaker
                );
            }
            return new List<CircuitBreaker>(CircuitBreakerList);
        }
    }
}